### ISSUE TITLE
Issues with test_plot_corr.py

### ISSUE THREAD

**Issue by dol23asuka** [UBC-MDS/snapedautility#15]
@dol23asuka 

code coverage is 66%

**Comment by AraiYuno** [comment]
![image](https://user-images.githubusercontent.com/28745975/150459618-585fc9b5-1cf8-4a9d-ad5f-a4bdcb7b21a9.png)
@dol23asuka 
One of the ways to clean unit tests so it is easier to read is to separate the unit test by branch (test case).
We have `test_corr_plot()` function that includes all the unit test cases. Let's separate them maybe!

**Comment by dol23asuka** [comment]
Make sense. will look into that and make changes later soon.

**Comment by dol23asuka** [comment]
Fixed.
