### ISSUE TITLE
Write test cases and code for function detect_outliers

### ISSUE THREAD

**Issue by harryyikhchan** [UBC-MDS/snapedautility#17]

**Comment by harryyikhchan** [comment]
Finished the function detect_outliers
Added three test case in test_detect_outliers

**Comment by AraiYuno** [comment]
![image](https://user-images.githubusercontent.com/28745975/150458732-e76c99b7-94c7-406b-8fc1-bac1864f8692.png)
Hey @harryyikhchan. I see some warnings in your unit test. It shouldn't be a problem since it's just a warning, but just heads up.

**Comment by harryyikhchan** [comment]
Got it, fixing it now

**Comment by AraiYuno** [comment]
![image](https://user-images.githubusercontent.com/28745975/150459491-fe0469ea-c6bf-40bb-b076-04532fae139d.png)
Here is one suggestion.

You have written one test case for each input type. Simply adding a couple of cases for each unit test function would be wonderful!

**Comment by harryyikhchan** [comment]
Thanks for the suggestion! will be included in the upcoming PR
