### ISSUE TITLE
Write test cases and code for function plot_corr

### ISSUE THREAD

**Issue by harryyikhchan** [UBC-MDS/snapedautility#18]

**Comment by AraiYuno** [comment]
@dol23asuka 
It looks like that test coverage is at 33%. Any issues?
![image](https://user-images.githubusercontent.com/28745975/150455646-089718c0-1e42-45be-b3c0-49ed095e72fb.png)

**Comment by harryyikhchan** [comment]
This is the progress percentage-value. Need to add the argument `--cov`
![image](https://user-images.githubusercontent.com/12680734/150456837-25227619-33b4-4b38-8628-d828b510d662.png)
