### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by harryyikhchan** [UBC-MDS/snapedautility#4]

**Comment by AraiYuno** [comment]
@harryyikhchan  @dol23asuka  
What about adding a usage section based on our function specifications?

**Comment by dol23asuka** [comment]
> 

Yes. Let's add specifications based on our docstrings.

**Comment by AraiYuno** [comment]
![image](https://user-images.githubusercontent.com/28745975/149572842-432ed5f7-0522-4f0e-aefe-3e2a68e14b77.png)
Here is an example. What do you think @harryyikhchan ?

**Comment by harryyikhchan** [comment]
Yes, looks good to me.

**Comment by harryyikhchan** [comment]
Update in PR #12
