### ISSUE TITLE
Issues with plot_corr function

### ISSUE THREAD

**Issue by dol23asuka** [UBC-MDS/snapedautility#7]
This is to track the progress of issues with plot_corr function

**Comment by AraiYuno** [comment]
![image](https://user-images.githubusercontent.com/28745975/149573036-e0c114d2-5a12-456c-80fa-39ca4fed3fca.png)
@harryyikhchan  @dol23asuka 
Hey, I just reviewed your code. It seems that the default height and width of the plots are set to 500 pixels. Wouldn't it be too big? Could you change them to something smaller?

**Comment by dol23asuka** [comment]
Yes I'll look into that and make a new pull request
